In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("../data/raw/mm_master_demos.csv")
df.head()

,Unnamed: 0,file,map,date,round,tick,seconds,att_team,vic_team,att_side,...,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y,round_type,ct_eq_val,t_eq_val,avg_match_rank
0,0,003201673717864202280_0171883906.dem,de_dust2,09/28/2017 8:44:22 PM,1,8482,133.0582,Team 1,Team 2,CounterTerrorist,...,76561198123082770,17,1473.847,1351.358,662.170,772.748,PISTOL_ROUND,2950,3850,16.0
1,1,003201673717864202280_0171883906.dem,de_dust2,09/28/2017 8:44:22 PM,1,8600,134.9023,Team 1,Team 2,CounterTerrorist,...,76561198051040004,17,-1211.723,1060.813,-1184.006,1153.343,PISTOL_ROUND,2950,3850,16.0
2,2,003201673717864202280_0171883906.dem,de_dust2,09/28/2017 8:44:22 PM,1,8610,135.0586,Team 2,Team 1,Terrorist,...,76561198223006752,16,-1153.584,1163.131,-1198.015,1050.423,PISTOL_ROUND,2950,3850,16.0
3,3,003201673717864202280_0171883906.dem,de_dust2,09/28/2017 8:44:22 PM,1,8624,135.2774,Team 1,Team 2,CounterTerrorist,...,76561198051040004,17,-1173.053,1044.365,-1141.785,1190.089,PISTOL_ROUND,2950,3850,16.0
4,4,003201673717864202280_0171883906.dem,de_dust2,09/28/2017 8:44:22 PM,1,8632,135.4024,Team 2,Team 1,Terrorist,...,76561198223006752,16,-1142.522,1200.967,-1157.690,1050.702,PISTOL_ROUND,2950,3850,16.0

In [12]:
df.dtypes

Unnamed: 0           int64
file                   str
map                    str
date                   str
round                int64
tick                 int64
seconds            float64
att_team               str
vic_team               str
att_side               str
vic_side               str
hp_dmg               int64
arm_dmg              int64
is_bomb_planted       bool
bomb_site              str
hitbox                 str
wp                     str
wp_type                str
award                int64
winner_team            str
winner_side            str
att_id               int64
att_rank             int64
vic_id               int64
vic_rank             int64
att_pos_x          float64
att_pos_y          float64
vic_pos_x          float64
vic_pos_y          float64
round_type             str
ct_eq_val            int64
t_eq_val             int64
avg_match_rank     float64
dtype: object

In [13]:
df["round"].value_counts()

round
2     41700
17    41562
3     39930
4     38960
18    38861
16    37672
1     37461
5     36871
6     36571
14    36443
13    36392
19    36333
10    36225
7     36027
15    35965
12    35831
9     35742
8     35602
11    35566
20    34183
21    32734
22    30639
23    28724
24    26156
25    22847
26    19914
27    17135
28    13837
29    11468
30     8115
Name: count, dtype: int64

In [14]:
df.describe(include='all')

,Unnamed: 0,file,map,date,round,tick,seconds,att_team,vic_team,att_side,...,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y,round_type,ct_eq_val,t_eq_val,avg_match_rank
count,955466.000000,955466,955466,955466,955466.000000,955466.000000,955466.000000,955466,955466,945474,...,9.554660e+05,955466.000000,955466.000000,955466.000000,955466.000000,955466.000000,955466,955466.000000,955466.000000,955466.000000
unique,NaN,1297,21,1079,NaN,NaN,NaN,27,26,2,...,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN
top,NaN,003233289942792667226_1563990910.dem,de_mirage,09/20/2017 10:36:10 AM,NaN,NaN,NaN,Team 1,Team 2,CounterTerrorist,...,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,NaN,NaN,NaN
freq,NaN,1160,267436,11434,NaN,NaN,NaN,475498,477712,489795,...,NaN,NaN,NaN,NaN,NaN,NaN,425090,NaN,NaN,NaN
mean,382.642960,NaN,NaN,NaN,13.514743,85875.182453,1342.276963,NaN,NaN,NaN,...,7.656120e+16,11.180971,-231.748882,260.942681,-230.312331,260.551225,NaN,18433.989279,18082.757995,11.199202
std,234.732587,NaN,NaN,NaN,7.852225,48707.523095,761.059254,NaN,NaN,NaN,...,1.274490e+08,3.036493,1161.032073,1375.098606,1153.964685,1368.173460,NaN,9516.829172,8305.133869,2.570913
min,0.000000,NaN,NaN,NaN,1.000000,6124.000000,96.139550,NaN,NaN,NaN,...,7.656120e+16,0.000000,-9987.305000,-4355.999000,-10027.000000,-4358.220000,NaN,800.000000,1000.000000,7.000000
25%,184.000000,NaN,NaN,NaN,7.000000,43735.000000,683.826700,NaN,NaN,NaN,...,7.656120e+16,9.000000,-953.375225,-737.916700,-948.403150,-740.760925,NaN,10300.000000,12500.000000,9.000000
50%,369.000000,NaN,NaN,NaN,13.000000,85417.000000,1335.137000,NaN,NaN,NaN,...,7.656120e+16,11.000000,-142.640800,243.367350,-127.884850,249.959750,NaN,20300.000000,20150.000000,11.000000
75%,563.000000,NaN,NaN,NaN,20.000000,122765.000000,1918.651750,NaN,NaN,NaN,...,7.656120e+16,13.000000,559.555200,1353.090750,556.154750,1352.738500,NaN,26450.000000,24750.000000,13.000000
max,1159.000000,NaN,NaN,NaN,30.000000,226841.000000,3544.908000,NaN,NaN,NaN,...,7.656120e+16,18.000000,7439.996000,14000.000000,7439.969000,14077.970000,NaN,39000.000000,38700.000000,16.000000

In [15]:
df["att_team"].value_counts()

att_team
Team 1                     475498
Team 2                     456810
World                       10524
Silver-Bullets.Gaming        2999
Patho-Logy Gaming             776
VERDITER GAMING               683
Totalmente Gamers             575
FrønT Gaming                  519
BayabasGaming                 482
` Je Veux | CS:GO Group       465
Øse Esport                    446
Naughty Penguin CS:GO         422
Black Guarrilla Family        421
[tercios]                     417
=Boosters=                    412
IBUYPOWER.Academy             407
Your-Worst-Nightmare          406
Surtant PoldPold!             386
GORZALA TEAM                  381
Defex eSports                 367
a y y l m a o                 351
ViCa GaminG                   342
Resurrect ESports-            319
ElectrichkaBOIZ               271
FragParty                     268
Grand Duchy Gaming            262
COW.BOYS                      257
Name: count, dtype: int64

Those with a well-defined team are in the low counts, so it's not worth studying team-by-team analytics.

In [16]:
df.loc[df['att_team'] == 'Øse Esport', 'avg_match_rank']

934762    13.0
934765    13.0
934767    13.0
934772    13.0
934778    13.0
          ...
935677    13.0
935678    13.0
935680    13.0
935683    13.0
935684    13.0
Name: avg_match_rank, Length: 446, dtype: float64

After checking that they're of different ranks, I thought that a team that already has chemistry would have more predictable positioning and might vary from the positioning of a player on solo queue. Additionally, since we don't want deaths not caused by players to skew our statistical tests and data analysis, I will only include Team 1 and Team 2 for att_team.

In [17]:
df1 = df[df["att_team"].isin(["Team 1", "Team 2"])]
df1["att_team"].value_counts()

att_team
Team 1    475498
Team 2    456810
Name: count, dtype: int64

In [18]:
df1["vic_team"].value_counts()

vic_team
Team 2                     467662
Team 1                     452184
Silver-Bullets.Gaming        2991
Patho-Logy Gaming             798
VERDITER GAMING               697
Totalmente Gamers             584
FrønT Gaming                  527
BayabasGaming                 468
Øse Esport                    465
IBUYPOWER.Academy             431
Naughty Penguin CS:GO         431
[tercios]                     407
` Je Veux | CS:GO Group       403
Defex eSports                 400
Surtant PoldPold!             377
GORZALA TEAM                  369
ViCa GaminG                   366
=Boosters=                    362
a y y l m a o                 333
COW.BOYS                      326
Your-Worst-Nightmare          320
Black Guarrilla Family        316
FragParty                     301
ElectrichkaBOIZ               273
Grand Duchy Gaming            266
Resurrect ESports-            251
Name: count, dtype: int64

We will do the same for the victim team.

In [19]:
df2 = df1[df1["vic_team"].isin(["Team 1", "Team 2"])]
df2["vic_team"].value_counts()

vic_team
Team 2    467662
Team 1    452184
Name: count, dtype: int64

In [20]:
df2.shape

(919846, 33)

In [21]:
df2.describe(include='all')

,Unnamed: 0,file,map,date,round,tick,seconds,att_team,vic_team,att_side,...,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y,round_type,ct_eq_val,t_eq_val,avg_match_rank
count,919846.000000,919846,919846,919846,919846.000000,919846.000000,919846.000000,919846,919846,919846,...,9.198460e+05,919846.000000,919846.000000,919846.000000,919846.000000,919846.000000,919846,919846.000000,919846.000000,919846.000000
unique,NaN,1295,21,1077,NaN,NaN,NaN,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN
top,NaN,003233289942792667226_1563990910.dem,de_mirage,09/20/2017 10:36:10 AM,NaN,NaN,NaN,Team 1,Team 2,CounterTerrorist,...,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,NaN,NaN,NaN
freq,NaN,1153,261150,10539,NaN,NaN,NaN,467417,467662,476728,...,NaN,NaN,NaN,NaN,NaN,NaN,409277,NaN,NaN,NaN
mean,382.258765,NaN,NaN,NaN,13.512390,85777.153807,1340.745764,NaN,NaN,NaN,...,7.656120e+16,11.177792,-239.087394,261.144898,-237.698014,260.657007,NaN,18437.029731,18063.208841,11.197798
std,234.716248,NaN,NaN,NaN,7.854271,48693.237218,760.836112,NaN,NaN,NaN,...,1.276441e+08,3.041144,1155.777512,1378.698304,1148.322957,1371.517216,NaN,9517.468157,8309.664084,2.576952
min,0.000000,NaN,NaN,NaN,1.000000,6124.000000,96.139550,NaN,NaN,NaN,...,7.656120e+16,0.000000,-9927.000000,-3467.919000,-10027.000000,-3459.950000,NaN,800.000000,1000.000000,7.000000
25%,183.000000,NaN,NaN,NaN,7.000000,43615.250000,681.983100,NaN,NaN,NaN,...,7.656120e+16,9.000000,-968.702675,-751.180025,-964.093900,-754.000000,NaN,10300.000000,12450.000000,9.000000
50%,369.000000,NaN,NaN,NaN,13.000000,85340.000000,1333.949000,NaN,NaN,NaN,...,7.656120e+16,11.000000,-160.140750,264.100050,-144.498850,272.510950,NaN,20300.000000,20150.000000,11.000000
75%,563.000000,NaN,NaN,NaN,20.000000,122670.000000,1917.177500,NaN,NaN,NaN,...,7.656120e+16,13.000000,563.968800,1362.077750,560.792125,1362.417500,NaN,26450.000000,24750.000000,13.000000
max,1159.000000,NaN,NaN,NaN,30.000000,226841.000000,3544.908000,NaN,NaN,NaN,...,7.656120e+16,18.000000,7439.996000,14000.000000,7439.969000,14064.000000,NaN,39000.000000,38700.000000,16.000000

In [22]:
df2.dtypes

Unnamed: 0           int64
file                   str
map                    str
date                   str
round                int64
tick                 int64
seconds            float64
att_team               str
vic_team               str
att_side               str
vic_side               str
hp_dmg               int64
arm_dmg              int64
is_bomb_planted       bool
bomb_site              str
hitbox                 str
wp                     str
wp_type                str
award                int64
winner_team            str
winner_side            str
att_id               int64
att_rank             int64
vic_id               int64
vic_rank             int64
att_pos_x          float64
att_pos_y          float64
vic_pos_x          float64
vic_pos_y          float64
round_type             str
ct_eq_val            int64
t_eq_val             int64
avg_match_rank     float64
dtype: object

In [23]:
df2.isna().sum()

Unnamed: 0              0
file                    0
map                     0
date                    0
round                   0
tick                    0
seconds                 0
att_team                0
vic_team                0
att_side                0
vic_side                0
hp_dmg                  0
arm_dmg                 0
is_bomb_planted         0
bomb_site          778790
hitbox                  0
wp                      0
wp_type                 0
award                   0
winner_team             0
winner_side             0
att_id                  0
att_rank                0
vic_id                  0
vic_rank                0
att_pos_x               0
att_pos_y               0
vic_pos_x               0
vic_pos_y               0
round_type              0
ct_eq_val               0
t_eq_val                0
avg_match_rank          0
dtype: int64

In [24]:
df2.loc[df2['att_side'].isnull(), 'att_team'].unique()

<StringArray>
[]
Length: 0, dtype: str

Let's do one more check.

In [25]:
df2["hp_dmg"].describe()

count    919846.000000
mean         27.413950
std          22.971165
min           0.000000
25%          14.000000
50%          22.000000
75%          29.000000
max         100.000000
Name: hp_dmg, dtype: float64

In [26]:
df2["arm_dmg"].describe()

count    919846.000000
mean          3.650439
std           4.595417
min           0.000000
25%           0.000000
50%           3.000000
75%           5.000000
max          34.000000
Name: arm_dmg, dtype: float64

In [27]:
df2["hitbox"].value_counts()

hitbox
Chest       368704
Stomach     190679
Head        109256
Generic      80645
RightArm     66335
RightLeg     40865
LeftLeg      37946
LeftArm      25416
Name: count, dtype: int64

In [28]:
df2["award"].describe()

count    919846.000000
mean        345.968238
std         152.935651
min           0.000000
25%         300.000000
50%         300.000000
75%         300.000000
max        1500.000000
Name: award, dtype: float64

In [29]:
df2["map"].value_counts()

map
de_mirage       261150
de_dust2        211264
de_cache        167107
de_inferno      117853
de_overpass      57355
de_cbble         46868
de_train         25486
de_nuke          10494
cs_office         4433
de_thrill         3576
cs_agency         3015
de_vertigo        2523
de_canals         1723
de_austria        1505
cs_italy          1349
de_dust           1333
de_shipped         970
cs_assault         697
de_blackgold       589
de_aztec           537
cs_insertion        19
Name: count, dtype: int64

In [30]:
df2[df2['map'] == "de_mirage"].describe()

,Unnamed: 0,round,tick,seconds,hp_dmg,arm_dmg,award,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y,ct_eq_val,t_eq_val,avg_match_rank
count,261150.000000,261150.000000,261150.000000,261150.000000,261150.000000,261150.000000,261150.000000,2.611500e+05,261150.000000,2.611500e+05,261150.00000,261150.000000,261150.000000,261150.000000,261150.000000,261150.000000,261150.000000,261150.000000
mean,377.235796,13.384871,85279.837971,1332.979386,27.438752,3.605667,342.899100,7.656120e+16,10.711181,7.656120e+16,10.60005,-739.479108,-902.476152,-715.848100,-902.236681,18427.909630,17782.394984,10.621704
std,233.378477,7.844069,48687.863338,760.754855,22.900920,4.582484,148.824345,1.280389e+08,2.877295,1.276490e+08,2.92358,848.619473,1005.923894,850.307971,1003.627228,9501.014088,8272.154315,2.402069
min,0.000000,1.000000,6729.000000,105.601400,0.000000,0.000000,0.000000,7.656120e+16,0.000000,7.656120e+16,0.00000,-2655.999000,-2603.104000,-2655.969000,-2603.110000,1000.000000,1000.000000,7.000000
25%,180.000000,7.000000,43052.250000,673.219375,14.000000,0.000000,300.000000,7.656120e+16,9.000000,7.656120e+16,9.00000,-1236.692750,-1691.045000,-1228.929750,-1672.884000,10400.000000,11900.000000,9.000000
50%,363.000000,13.000000,84529.000000,1321.259500,22.000000,3.000000,300.000000,7.656120e+16,10.000000,7.656120e+16,10.00000,-696.809800,-1010.742500,-676.219300,-1023.417500,20350.000000,19900.000000,10.000000
75%,556.000000,20.000000,122034.000000,1907.284250,30.000000,4.000000,300.000000,7.656120e+16,13.000000,7.656120e+16,13.00000,-93.314685,-11.312428,-56.182543,-28.161147,26450.000000,24450.000000,12.000000
max,1072.000000,30.000000,224068.000000,3501.649000,100.000000,34.000000,1500.000000,7.656120e+16,18.000000,7.656120e+16,18.00000,1455.834000,887.984200,1455.836000,887.968800,37450.000000,35850.000000,16.000000

Actually, we only have map data for seven maps, so let's filter that.

In [31]:
map_list = ["de_cache", "de_cbble", "de_dust2", "de_inferno", "de_mirage", "de_overpass", "de_train"]

df3 = df2[df2["map"].isin(map_list)]
df3["map"].value_counts()

map
de_mirage      261150
de_dust2       211264
de_cache       167107
de_inferno     117853
de_overpass     57355
de_cbble        46868
de_train        25486
Name: count, dtype: int64

In [32]:
df3.shape

(887083, 33)

There is no "rank 0" in the rank list according to https://totalcsgo.com/ranks

In [33]:
df4 = df3[(df3["att_rank"] > 0) & (df3["vic_rank"] > 0)]
print(df4["att_rank"].value_counts())
print(df4["vic_rank"].value_counts())

att_rank
10    116037
9     109769
11    100369
13    100289
12     96747
14     84569
8      67829
15     58321
16     51403
7      41515
17     17921
6      11443
5       3389
18      2322
4       1882
3        630
2        401
1        144
Name: count, dtype: int64
vic_rank
10    114021
9     110964
11     99850
13     98001
12     97019
14     82483
8      71036
15     55963
16     50273
7      44662
17     17098
6      12924
5       4465
4       2408
18      1825
3       1064
2        656
1        268
Name: count, dtype: int64

NOTE: We need to confirm whether the coordinates are consistent with the map data. Probably use SQL JOINs for this.

In [34]:
df4.isna().sum()

Unnamed: 0              0
file                    0
map                     0
date                    0
round                   0
tick                    0
seconds                 0
att_team                0
vic_team                0
att_side                0
vic_side                0
hp_dmg                  0
arm_dmg                 0
is_bomb_planted         0
bomb_site          731024
hitbox                  0
wp                      0
wp_type                 0
award                   0
winner_team             0
winner_side             0
att_id                  0
att_rank                0
vic_id                  0
vic_rank                0
att_pos_x               0
att_pos_y               0
vic_pos_x               0
vic_pos_y               0
round_type              0
ct_eq_val               0
t_eq_val                0
avg_match_rank          0
dtype: int64

In [35]:
df4.describe(include='all')

,Unnamed: 0,file,map,date,round,tick,seconds,att_team,vic_team,att_side,...,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y,round_type,ct_eq_val,t_eq_val,avg_match_rank
count,864980.000000,864980,864980,864980,864980.000000,864980.000000,864980.000000,864980,864980,864980,...,8.649800e+05,864980.000000,864980.000000,864980.000000,864980.000000,864980.000000,864980,864980.00000,864980.000000,864980.000000
unique,NaN,1246,7,1039,NaN,NaN,NaN,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN
top,NaN,003233289942792667226_1563990910.dem,de_mirage,09/20/2017 10:36:10 AM,NaN,NaN,NaN,Team 1,Team 2,CounterTerrorist,...,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,NaN,NaN,NaN
freq,NaN,1153,253980,10216,NaN,NaN,NaN,438639,438980,448244,...,NaN,NaN,NaN,NaN,NaN,NaN,384130,NaN,NaN,NaN
mean,382.199365,NaN,NaN,NaN,13.532604,86018.291574,1344.514013,NaN,NaN,NaN,...,7.656120e+16,11.321375,-257.829968,277.750771,-255.965669,277.578753,NaN,18435.66753,18091.151183,11.232780
std,234.401992,NaN,NaN,NaN,7.859895,48787.121184,762.303255,NaN,NaN,NaN,...,1.268851e+08,2.774999,1148.132392,1382.608052,1141.048018,1374.770072,NaN,9544.99320,8328.372164,2.577903
min,0.000000,NaN,NaN,NaN,1.000000,6124.000000,96.139550,NaN,NaN,NaN,...,7.656120e+16,1.000000,-3960.000000,-3467.919000,-3959.999000,-3459.950000,NaN,800.00000,1000.000000,7.000000
25%,183.000000,NaN,NaN,NaN,7.000000,43785.000000,684.627625,NaN,NaN,NaN,...,7.656120e+16,9.000000,-983.899025,-738.982900,-979.056900,-740.853475,NaN,10200.00000,12500.000000,9.000000
50%,369.000000,NaN,NaN,NaN,13.000000,85672.500000,1339.111000,NaN,NaN,NaN,...,7.656120e+16,11.000000,-178.417950,290.270250,-161.951400,298.974600,NaN,20350.00000,20200.000000,11.000000
75%,563.000000,NaN,NaN,NaN,20.000000,122977.000000,1921.996500,NaN,NaN,NaN,...,7.656120e+16,13.000000,546.914500,1385.188250,546.045625,1386.805000,NaN,26500.00000,24800.000000,13.000000
max,1159.000000,NaN,NaN,NaN,30.000000,226841.000000,3544.908000,NaN,NaN,NaN,...,7.656120e+16,18.000000,3309.969000,3592.000000,3178.983000,3592.000000,NaN,39000.00000,38700.000000,16.000000

In [36]:
df4.duplicated().sum()

np.int64(0)

I think this is good to go for SQL stuff?

In [37]:
df4["wp_type"].value_counts()

wp_type
Rifle        385100
Pistol       175643
SMG          162769
Grenade       74318
Sniper        45853
Heavy         18960
Equipment      2333
Unkown            4
Name: count, dtype: int64

In [38]:
df4.loc[df['wp_type'] == 'Unkown', 'wp_type'] = 'Unknown'
df4["wp_type"].value_counts()

wp_type
Rifle        385100
Pistol       175643
SMG          162769
Grenade       74318
Sniper        45853
Heavy         18960
Equipment      2333
Unknown           4
Name: count, dtype: int64

In [40]:
import os

folder_path = '../data/processed'
file_name = 'csgo_cleaned_1.csv'
full_path = os.path.join(folder_path, file_name)

df4.to_csv(full_path, index=False)
print(f"File successfully saved to: {full_path}")

File successfully saved to: ../data/processed\csgo_cleaned_1.csv

Let's do a quick check of the map data csv:

In [41]:
df = pd.read_csv("../data/raw/map_data.csv")
df.rename(columns={'Unnamed: 0': 'map'}, inplace=True)
df.head(7)

           map  EndX  EndY  ResX  ResY  StartX  StartY
0     de_cache  3752  3187  1024  1024   -2031   -2240
1     de_cbble  2282  3032  1024  1024   -3819   -3073
2     de_dust2  2127  3455  1024  1024   -2486   -1150
3   de_inferno  2797  3800  1024  1024   -1960   -1062
4    de_mirage  1912  1682  1024  1024   -3217   -3401
5  de_overpass   503  1740  1024  1024   -4820   -3591
6     de_train  2262  2447  1024  1024   -2436   -2469

Looks good.

In [42]:
folder_path = '../data/processed'
file_name = 'map_data.csv'
full_path = os.path.join(folder_path, file_name)

df.to_csv(full_path, index=False)
print(f"File successfully saved to: {full_path}")

File successfully saved to: ../data/processed\map_data.csv