In [90]:
import pandas as pd

In [91]:
df = pd.read_csv("../data/raw/mm_master_demos.csv")
df.head()

,Unnamed: 0,file,map,date,round,tick,seconds,att_team,vic_team,att_side,...,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y,round_type,ct_eq_val,t_eq_val,avg_match_rank
0,0,003201673717864202280_0171883906.dem,de_dust2,09/28/2017 8:44:22 PM,1,8482,133.0582,Team 1,Team 2,CounterTerrorist,...,76561198123082770,17,1473.847,1351.358,662.170,772.748,PISTOL_ROUND,2950,3850,16.0
1,1,003201673717864202280_0171883906.dem,de_dust2,09/28/2017 8:44:22 PM,1,8600,134.9023,Team 1,Team 2,CounterTerrorist,...,76561198051040004,17,-1211.723,1060.813,-1184.006,1153.343,PISTOL_ROUND,2950,3850,16.0
2,2,003201673717864202280_0171883906.dem,de_dust2,09/28/2017 8:44:22 PM,1,8610,135.0586,Team 2,Team 1,Terrorist,...,76561198223006752,16,-1153.584,1163.131,-1198.015,1050.423,PISTOL_ROUND,2950,3850,16.0
3,3,003201673717864202280_0171883906.dem,de_dust2,09/28/2017 8:44:22 PM,1,8624,135.2774,Team 1,Team 2,CounterTerrorist,...,76561198051040004,17,-1173.053,1044.365,-1141.785,1190.089,PISTOL_ROUND,2950,3850,16.0
4,4,003201673717864202280_0171883906.dem,de_dust2,09/28/2017 8:44:22 PM,1,8632,135.4024,Team 2,Team 1,Terrorist,...,76561198223006752,16,-1142.522,1200.967,-1157.690,1050.702,PISTOL_ROUND,2950,3850,16.0

In [92]:
df.dtypes

Unnamed: 0           int64
file                   str
map                    str
date                   str
round                int64
tick                 int64
seconds            float64
att_team               str
vic_team               str
att_side               str
vic_side               str
hp_dmg               int64
arm_dmg              int64
is_bomb_planted       bool
bomb_site              str
hitbox                 str
wp                     str
wp_type                str
award                int64
winner_team            str
winner_side            str
att_id               int64
att_rank             int64
vic_id               int64
vic_rank             int64
att_pos_x          float64
att_pos_y          float64
vic_pos_x          float64
vic_pos_y          float64
round_type             str
ct_eq_val            int64
t_eq_val             int64
avg_match_rank     float64
dtype: object

In [93]:
df["round"].value_counts()

round
2     41700
17    41562
3     39930
4     38960
18    38861
16    37672
1     37461
5     36871
6     36571
14    36443
13    36392
19    36333
10    36225
7     36027
15    35965
12    35831
9     35742
8     35602
11    35566
20    34183
21    32734
22    30639
23    28724
24    26156
25    22847
26    19914
27    17135
28    13837
29    11468
30     8115
Name: count, dtype: int64

In [94]:
df.describe(include='all')

,Unnamed: 0,file,map,date,round,tick,seconds,att_team,vic_team,att_side,...,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y,round_type,ct_eq_val,t_eq_val,avg_match_rank
count,955466.000000,955466,955466,955466,955466.000000,955466.000000,955466.000000,955466,955466,945474,...,9.554660e+05,955466.000000,955466.000000,955466.000000,955466.000000,955466.000000,955466,955466.000000,955466.000000,955466.000000
unique,NaN,1297,21,1079,NaN,NaN,NaN,27,26,2,...,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN
top,NaN,003233289942792667226_1563990910.dem,de_mirage,09/20/2017 10:36:10 AM,NaN,NaN,NaN,Team 1,Team 2,CounterTerrorist,...,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,NaN,NaN,NaN
freq,NaN,1160,267436,11434,NaN,NaN,NaN,475498,477712,489795,...,NaN,NaN,NaN,NaN,NaN,NaN,425090,NaN,NaN,NaN
mean,382.642960,NaN,NaN,NaN,13.514743,85875.182453,1342.276963,NaN,NaN,NaN,...,7.656120e+16,11.180971,-231.748882,260.942681,-230.312331,260.551225,NaN,18433.989279,18082.757995,11.199202
std,234.732587,NaN,NaN,NaN,7.852225,48707.523095,761.059254,NaN,NaN,NaN,...,1.274490e+08,3.036493,1161.032073,1375.098606,1153.964685,1368.173460,NaN,9516.829172,8305.133869,2.570913
min,0.000000,NaN,NaN,NaN,1.000000,6124.000000,96.139550,NaN,NaN,NaN,...,7.656120e+16,0.000000,-9987.305000,-4355.999000,-10027.000000,-4358.220000,NaN,800.000000,1000.000000,7.000000
25%,184.000000,NaN,NaN,NaN,7.000000,43735.000000,683.826700,NaN,NaN,NaN,...,7.656120e+16,9.000000,-953.375225,-737.916700,-948.403150,-740.760925,NaN,10300.000000,12500.000000,9.000000
50%,369.000000,NaN,NaN,NaN,13.000000,85417.000000,1335.137000,NaN,NaN,NaN,...,7.656120e+16,11.000000,-142.640800,243.367350,-127.884850,249.959750,NaN,20300.000000,20150.000000,11.000000
75%,563.000000,NaN,NaN,NaN,20.000000,122765.000000,1918.651750,NaN,NaN,NaN,...,7.656120e+16,13.000000,559.555200,1353.090750,556.154750,1352.738500,NaN,26450.000000,24750.000000,13.000000
max,1159.000000,NaN,NaN,NaN,30.000000,226841.000000,3544.908000,NaN,NaN,NaN,...,7.656120e+16,18.000000,7439.996000,14000.000000,7439.969000,14077.970000,NaN,39000.000000,38700.000000,16.000000

In [95]:
df["att_team"].value_counts()

att_team
Team 1                     475498
Team 2                     456810
World                       10524
Silver-Bullets.Gaming        2999
Patho-Logy Gaming             776
VERDITER GAMING               683
Totalmente Gamers             575
FrønT Gaming                  519
BayabasGaming                 482
` Je Veux | CS:GO Group       465
Øse Esport                    446
Naughty Penguin CS:GO         422
Black Guarrilla Family        421
[tercios]                     417
=Boosters=                    412
IBUYPOWER.Academy             407
Your-Worst-Nightmare          406
Surtant PoldPold!             386
GORZALA TEAM                  381
Defex eSports                 367
a y y l m a o                 351
ViCa GaminG                   342
Resurrect ESports-            319
ElectrichkaBOIZ               271
FragParty                     268
Grand Duchy Gaming            262
COW.BOYS                      257
Name: count, dtype: int64

Those with a well-defined team are in the low counts, so it's not worth studying team-by-team analytics.

In [96]:
df.loc[df['att_team'] == 'Øse Esport', 'avg_match_rank']

934762    13.0
934765    13.0
934767    13.0
934772    13.0
934778    13.0
          ...
935677    13.0
935678    13.0
935680    13.0
935683    13.0
935684    13.0
Name: avg_match_rank, Length: 446, dtype: float64

After checking that they're of different ranks, I thought that a team that already has chemistry would have more predictable positioning and might vary from the positioning of a player on solo queue. Hence, I will remove them.

In [97]:
df1 = df[df["att_team"].isin(["Team 1", "Team 2", "World"])]
df1["att_team"].value_counts()

att_team
Team 1    475498
Team 2    456810
World      10524
Name: count, dtype: int64

In [98]:
df1["vic_team"].value_counts()

vic_team
Team 2                     473151
Team 1                     457011
Silver-Bullets.Gaming        3045
Patho-Logy Gaming             806
VERDITER GAMING               720
Totalmente Gamers             604
FrønT Gaming                  531
Øse Esport                    475
BayabasGaming                 470
IBUYPOWER.Academy             445
Naughty Penguin CS:GO         432
Defex eSports                 409
` Je Veux | CS:GO Group       408
[tercios]                     407
Surtant PoldPold!             381
GORZALA TEAM                  374
ViCa GaminG                   373
=Boosters=                    367
a y y l m a o                 335
Black Guarrilla Family        330
COW.BOYS                      328
Your-Worst-Nightmare          321
FragParty                     308
ElectrichkaBOIZ               273
Grand Duchy Gaming            273
Resurrect ESports-            255
Name: count, dtype: int64

I'm assuming these are world victims. Let's check:

In [99]:
df1.loc[df['vic_team'] == 'Øse Esport', 'att_team']

934757    Team 1
934758    Team 1
934759    Team 1
934760    Team 1
934761    Team 1
           ...
935668    Team 1
935675    Team 1
935679    Team 1
935681    Team 1
935682    Team 1
Name: att_team, Length: 475, dtype: str

Nevermind. I'd still remove them.

In [100]:
df2 = df[df["vic_team"].isin(["Team 1", "Team 2"])]
df2["vic_team"].value_counts()

vic_team
Team 2    477712
Team 1    464633
Name: count, dtype: int64

In [101]:
df2.shape

(942345, 33)

In [102]:
df2.describe(include='all')

,Unnamed: 0,file,map,date,round,tick,seconds,att_team,vic_team,att_side,...,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y,round_type,ct_eq_val,t_eq_val,avg_match_rank
count,942345.000000,942345,942345,942345,942345.000000,942345.000000,942345.000000,942345,942345,932549,...,9.423450e+05,942345.000000,942345.000000,942345.000000,942345.000000,942345.000000,942345,942345.000000,942345.000000,942345.000000
unique,NaN,1297,21,1079,NaN,NaN,NaN,27,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN
top,NaN,003233289942792667226_1563990910.dem,de_mirage,09/20/2017 10:36:10 AM,NaN,NaN,NaN,Team 1,Team 2,CounterTerrorist,...,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,NaN,NaN,NaN
freq,NaN,1160,265322,11039,NaN,NaN,NaN,467417,477712,482763,...,NaN,NaN,NaN,NaN,NaN,NaN,419290,NaN,NaN,NaN
mean,382.580009,NaN,NaN,NaN,13.516714,85857.354172,1341.998641,NaN,NaN,NaN,...,7.656120e+16,11.181148,-233.802814,259.858372,-232.266283,259.213572,NaN,18434.106193,18082.716415,11.198572
std,234.726297,NaN,NaN,NaN,7.852798,48701.475821,760.964788,NaN,NaN,NaN,...,1.275090e+08,3.036198,1155.828370,1373.723396,1148.785751,1366.609824,NaN,9517.686592,8303.573421,2.574242
min,0.000000,NaN,NaN,NaN,1.000000,6124.000000,96.139550,NaN,NaN,NaN,...,7.656120e+16,0.000000,-9927.000000,-4131.491000,-10027.000000,-4358.220000,NaN,800.000000,1000.000000,7.000000
25%,184.000000,NaN,NaN,NaN,7.000000,43716.000000,683.515100,NaN,NaN,NaN,...,7.656120e+16,9.000000,-955.071200,-737.966700,-949.701700,-740.910800,NaN,10300.000000,12500.000000,9.000000
50%,369.000000,NaN,NaN,NaN,13.000000,85400.000000,1334.847000,NaN,NaN,NaN,...,7.656120e+16,11.000000,-143.030200,244.353900,-129.257400,250.562200,NaN,20300.000000,20150.000000,11.000000
75%,563.000000,NaN,NaN,NaN,20.000000,122756.000000,1918.506000,NaN,NaN,NaN,...,7.656120e+16,13.000000,558.201800,1353.229000,555.172800,1352.060000,NaN,26450.000000,24750.000000,13.000000
max,1159.000000,NaN,NaN,NaN,30.000000,226841.000000,3544.908000,NaN,NaN,NaN,...,7.656120e+16,18.000000,7439.996000,14000.000000,7439.969000,14064.000000,NaN,39000.000000,38700.000000,16.000000

In [103]:
df2.dtypes

Unnamed: 0           int64
file                   str
map                    str
date                   str
round                int64
tick                 int64
seconds            float64
att_team               str
vic_team               str
att_side               str
vic_side               str
hp_dmg               int64
arm_dmg              int64
is_bomb_planted       bool
bomb_site              str
hitbox                 str
wp                     str
wp_type                str
award                int64
winner_team            str
winner_side            str
att_id               int64
att_rank             int64
vic_id               int64
vic_rank             int64
att_pos_x          float64
att_pos_y          float64
vic_pos_x          float64
vic_pos_y          float64
round_type             str
ct_eq_val            int64
t_eq_val             int64
avg_match_rank     float64
dtype: object

In [104]:
df2.isna().sum()

Unnamed: 0              0
file                    0
map                     0
date                    0
round                   0
tick                    0
seconds                 0
att_team                0
vic_team                0
att_side             9796
vic_side                0
hp_dmg                  0
arm_dmg                 0
is_bomb_planted         0
bomb_site          793518
hitbox                  0
wp                      0
wp_type                 0
award                   0
winner_team             0
winner_side             0
att_id                  0
att_rank                0
vic_id                  0
vic_rank                0
att_pos_x               0
att_pos_y               0
vic_pos_x               0
vic_pos_y               0
round_type              0
ct_eq_val               0
t_eq_val                0
avg_match_rank          0
dtype: int64

In [105]:
df2.loc[df2['att_side'].isnull(), 'att_team'].unique()

<StringArray>
['World']
Length: 1, dtype: str

Let's do one more check.

In [106]:
df2["hp_dmg"].describe()

count    942345.000000
mean         27.311998
std          23.001101
min           0.000000
25%          14.000000
50%          22.000000
75%          29.000000
max         100.000000
Name: hp_dmg, dtype: float64

In [107]:
df2["arm_dmg"].describe()

count    942345.000000
mean          3.718552
std           5.151262
min           0.000000
25%           0.000000
50%           3.000000
75%           5.000000
max         100.000000
Name: arm_dmg, dtype: float64

In [108]:
df2["hitbox"].value_counts()

hitbox
Chest       373784
Stomach     193427
Head        110751
Generic      91379
RightArm     67257
RightLeg     41478
LeftLeg      38506
LeftArm      25763
Name: count, dtype: int64

In [109]:
df2["award"].describe()

count    942345.000000
mean        342.347017
std         156.074427
min           0.000000
25%         300.000000
50%         300.000000
75%         300.000000
max        1500.000000
Name: award, dtype: float64

In [110]:
df2["map"].value_counts()

map
de_mirage       265322
de_dust2        215248
de_cache        172224
de_inferno      120187
de_overpass      59244
de_cbble         48435
de_train         26343
de_nuke          10741
cs_office         4829
de_thrill         3623
cs_agency         3204
de_vertigo        2571
de_canals         2442
de_austria        1520
cs_italy          1356
de_dust           1340
cs_assault        1167
de_shipped         979
de_blackgold       603
de_aztec           545
cs_insertion       422
Name: count, dtype: int64

In [111]:
df2[df2['map'] == "de_mirage"].describe()

,Unnamed: 0,round,tick,seconds,hp_dmg,arm_dmg,award,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y,ct_eq_val,t_eq_val,avg_match_rank
count,265322.000000,265322.000000,265322.000000,265322.000000,265322.000000,265322.000000,265322.000000,2.653220e+05,265322.000000,2.653220e+05,265322.000000,265322.000000,265322.000000,265322.000000,265322.000000,265322.000000,265322.000000,265322.000000
mean,377.246972,13.387653,85327.289648,1333.720855,27.409020,3.689381,340.370192,7.595003e+16,10.641941,7.656120e+16,10.615120,-733.047565,-897.014470,-710.147486,-896.789799,18412.316355,17804.044331,10.636675
std,233.293133,7.844390,48714.656250,761.173501,22.947226,5.179929,151.057357,6.813112e+15,3.023591,1.276721e+08,2.924872,847.653232,1005.143607,849.151838,1002.711363,9501.439577,8272.235261,2.406987
min,0.000000,1.000000,6729.000000,105.601400,0.000000,0.000000,0.000000,0.000000e+00,0.000000,7.656120e+16,0.000000,-2655.999000,-2603.104000,-2655.969000,-2603.110000,1000.000000,1000.000000,7.000000
25%,180.000000,7.000000,43091.000000,673.780050,14.000000,0.000000,300.000000,7.656120e+16,9.000000,7.656120e+16,9.000000,-1230.585500,-1687.620000,-1222.643000,-1669.154000,10350.000000,11950.000000,9.000000
50%,363.000000,13.000000,84551.000000,1321.632500,22.000000,3.000000,300.000000,7.656120e+16,10.000000,7.656120e+16,10.000000,-690.249700,-990.298200,-670.162100,-1006.126000,20300.000000,19900.000000,10.000000
75%,556.000000,20.000000,122083.750000,1908.036500,30.000000,5.000000,300.000000,7.656120e+16,13.000000,7.656120e+16,13.000000,-78.149612,0.000000,-36.816263,-0.503702,26400.000000,24500.000000,12.000000
max,1072.000000,30.000000,224068.000000,3501.649000,100.000000,100.000000,1500.000000,7.656120e+16,18.000000,7.656120e+16,18.000000,1455.834000,887.984200,1455.836000,887.968800,37450.000000,35850.000000,16.000000

Actually, we only have map data for seven maps, so let's filter that.

In [112]:
map_list = ["de_cache", "de_cbble", "de_dust2", "de_inferno", "de_mirage", "de_overpass", "de_train"]

df3 = df2[df2["map"].isin(map_list)]
df3["map"].value_counts()

map
de_mirage      265322
de_dust2       215248
de_cache       172224
de_inferno     120187
de_overpass     59244
de_cbble        48435
de_train        26343
Name: count, dtype: int64

In [113]:
df3.shape

(907003, 33)

There is no "rank 0" in the rank list according to https://totalcsgo.com/ranks

In [114]:
df4 = df3[(df3["att_rank"] > 0) & (df3["vic_rank"] > 0)]
print(df4["att_rank"].value_counts())
print(df4["vic_rank"].value_counts())

att_rank
10    117883
9     110681
11    101528
13    101240
12     97492
14     86027
8      68966
15     58749
16     52160
7      41806
17     18256
6      11556
5       3389
18      2322
4       1882
3        630
2        401
1        144
Name: count, dtype: int64
vic_rank
10    115590
9     112243
11    100802
12     99249
13     99089
14     83530
8      71605
15     56259
16     50648
7      45022
17     17417
6      12972
5       4465
4       2408
18      1825
3       1064
2        656
1        268
Name: count, dtype: int64

NOTE: We need to confirm whether the coordinates are consistent with the map data. Probably use SQL JOINs for this.

In [115]:
df4.isna().sum()

Unnamed: 0              0
file                    0
map                     0
date                    0
round                   0
tick                    0
seconds                 0
att_team                0
vic_team                0
att_side                0
vic_side                0
hp_dmg                  0
arm_dmg                 0
is_bomb_planted         0
bomb_site          739496
hitbox                  0
wp                      0
wp_type                 0
award                   0
winner_team             0
winner_side             0
att_id                  0
att_rank                0
vic_id                  0
vic_rank                0
att_pos_x               0
att_pos_y               0
vic_pos_x               0
vic_pos_y               0
round_type              0
ct_eq_val               0
t_eq_val                0
avg_match_rank          0
dtype: int64

In [116]:
df4.describe(include='all')

,Unnamed: 0,file,map,date,round,tick,seconds,att_team,vic_team,att_side,...,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y,round_type,ct_eq_val,t_eq_val,avg_match_rank
count,875112.000000,875112,875112,875112,875112.000000,875112.000000,875112.000000,875112,875112,875112,...,8.751120e+05,875112.000000,875112.000000,875112.000000,875112.000000,875112.000000,875112,875112.000000,875112.000000,875112.000000
unique,NaN,1248,7,1041,NaN,NaN,NaN,22,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN
top,NaN,003233289942792667226_1563990910.dem,de_mirage,09/20/2017 10:36:10 AM,NaN,NaN,NaN,Team 1,Team 2,CounterTerrorist,...,NaN,NaN,NaN,NaN,NaN,NaN,NORMAL,NaN,NaN,NaN
freq,NaN,1153,256034,10588,NaN,NaN,NaN,438639,442812,452970,...,NaN,NaN,NaN,NaN,NaN,NaN,388595,NaN,NaN,NaN
mean,382.222935,NaN,NaN,NaN,13.530587,86019.958396,1344.539889,NaN,NaN,NaN,...,7.656120e+16,11.323375,-257.713408,278.243054,-255.728375,277.895706,NaN,18433.174725,18094.331240,11.233877
std,234.435898,NaN,NaN,NaN,7.859856,48790.023340,762.348640,NaN,NaN,NaN,...,1.267983e+08,2.770913,1147.688049,1382.215859,1140.902829,1374.370739,NaN,9542.954850,8326.947996,2.575322
min,0.000000,NaN,NaN,NaN,1.000000,6124.000000,96.139550,NaN,NaN,NaN,...,7.656120e+16,1.000000,-3960.000000,-3467.919000,-3959.999000,-3459.950000,NaN,800.000000,1000.000000,7.000000
25%,183.000000,NaN,NaN,NaN,7.000000,43777.000000,684.490650,NaN,NaN,NaN,...,7.656120e+16,9.000000,-982.446600,-738.268650,-978.099850,-740.602975,NaN,10200.000000,12500.000000,9.000000
50%,369.000000,NaN,NaN,NaN,13.000000,85670.000000,1339.075000,NaN,NaN,NaN,...,7.656120e+16,11.000000,-177.673000,290.331450,-161.060300,298.663250,NaN,20350.000000,20200.000000,11.000000
75%,563.000000,NaN,NaN,NaN,20.000000,122981.000000,1922.066250,NaN,NaN,NaN,...,7.656120e+16,13.000000,546.225450,1385.630000,546.156600,1387.107250,NaN,26500.000000,24800.000000,13.000000
max,1159.000000,NaN,NaN,NaN,30.000000,226841.000000,3544.908000,NaN,NaN,NaN,...,7.656120e+16,18.000000,3309.969000,3592.000000,3178.983000,3592.000000,NaN,39000.000000,38700.000000,16.000000

In [117]:
df4.duplicated().sum()

np.int64(0)

I think this is good to go for SQL stuff?

In [118]:
df4["wp_type"].value_counts()

wp_type
Rifle        389875
Pistol       177653
SMG          164717
Grenade       74975
Sniper        46397
Heavy         19136
Equipment      2355
Unkown            4
Name: count, dtype: int64

In [119]:
df4.loc[df['wp_type'] == 'Unkown', 'wp_type'] = 'Unknown'
df4["wp_type"].value_counts()

wp_type
Rifle        389875
Pistol       177653
SMG          164717
Grenade       74975
Sniper        46397
Heavy         19136
Equipment      2355
Unknown           4
Name: count, dtype: int64

In [120]:
import os

folder_path = '../data/processed'
file_name = 'csgo_cleaned_1.csv'
full_path = os.path.join(folder_path, file_name)

df4.to_csv(full_path, index=False)
print(f"File successfully saved to: {full_path}")

File successfully saved to: ../data/processed\csgo_cleaned_1.csv

Let's do a quick check of the map data csv:

In [121]:
df = pd.read_csv("../data/raw/map_data.csv")
df.rename(columns={'Unnamed: 0': 'map'}, inplace=True)
df.head(7)

           map  EndX  EndY  ResX  ResY  StartX  StartY
0     de_cache  3752  3187  1024  1024   -2031   -2240
1     de_cbble  2282  3032  1024  1024   -3819   -3073
2     de_dust2  2127  3455  1024  1024   -2486   -1150
3   de_inferno  2797  3800  1024  1024   -1960   -1062
4    de_mirage  1912  1682  1024  1024   -3217   -3401
5  de_overpass   503  1740  1024  1024   -4820   -3591
6     de_train  2262  2447  1024  1024   -2436   -2469

Looks good.

In [122]:
folder_path = '../data/processed'
file_name = 'map_data.csv'
full_path = os.path.join(folder_path, file_name)

df.to_csv(full_path, index=False)
print(f"File successfully saved to: {full_path}")

File successfully saved to: ../data/processed\map_data.csv